# Generated by Django 4.2.2 on 2024-09-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
